version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ponto
      MYSQL_USER: ponto
      MYSQL_PASSWORD: ponto
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
   
volumes:
  mysql_data:
